name: Backend Tests

on:
  push:
    branches:
      - develop
      - backend
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore CurrencyObserver/CurrencyObserverWebAPI

      - name: Build
        run: dotnet build CurrencyObserver/CurrencyObserverWebAPI --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test CurrencyObserver/CurrencyObserverWebAPI --no-build --verbosity normal
