name: Backend Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore CurrencyObserver/CurrencyObserver.WebAPI

      - name: Build
        run: dotnet build CurrencyObserver/CurrencyObserver.WebAPI --no-restore --configuration Release

      - name: Publish
        run: dotnet publish CurrencyObserver/CurrencyObserver.WebAPI -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "CurrensyObserverWebAPI"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
